# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

plugin 'cocoapods-xccache'

target 'PluginDebug' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  cache_all!

  # Pods for PluginDebug
  pod 'SDWebImage', :cache => false
  pod 'AFNetworking'
  pod 'YYModel'

  target 'PluginDebugTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PluginDebugUITests' do
    # Pods for testing
  end

end
